### PR TITLE
Call readKeysFromPath on ObjectivePGP rather than self

### PR DESCRIPTION
**Pull request by culyun**
I'm not an IOS dev, but I needed to make this change to build.

### CODE REVIEW

**Comment by krzyzanowskim** [comment]
Thanks.
What happened? can you give more details how do you build to run into such issue?

**Comment by culyun** [comment]
I think PGPKeyring.importKey has a bug.  A fatal exception was thrown when I called importKey:

> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[PGPKeyring readKeysFromPath:error:]: unrecognized selector sent to class

I modified the code to call `[ObjectivePGP readKeysFromPath ...]` instead of `[self.class readKeysFromPath ...]`, which seemed to fix the problem.

**Comment by krzyzanowskim** [comment]
This is odd, self.class is fine, unless you subclass ObjectivePGP class maybe?

**Comment by culyun** [comment]
I wasn't subclassing, just calling importKey via the swift wrapper.

I couldn't figure out how `self.class` in PGPKeyring could resolve` readKeysFromPath` so that's why I made the change, which seemed to fix the issue.

**Comment by krzyzanowskim** [comment]
so `self` is an instant, and `self.class` is `ObjectivePGP` class. The syntax is fine. I'll merge this one just in case.

Could you share Xcode project to reproduce that? I'm very curious what the reason.

**Comment by krzyzanowskim** [comment]
I'm sorry, I fixated on `ObjectivePGP` instance. Right, this is due to refactoring. Wonder why compiler didn't warn ;)

**Comment by culyun** [comment]
No worries.  I'm simply hacking my way through things at the moment, but I have to say that swift is a good deal easier to read than objc!  Thanks for sharing your great library btw.

**Pull request merged**
