### PR TITLE
ECC support

### LINKED ISSUE #118: Importing exported key fails for specific public keys (EdDSA)
- ObjectivePGP version: 0.12.2
- Platform (iOS/macOS): All
- Installation method (CocoaPods/Carthage/...): Cocoapods
- Project name: Canary

# Description

Importing a public key using `readKeysFromData:error:` exported using `export:` fails for a particular key:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: SKS 1.1.6
Comment: Hostname: sks-nyc.semperen.com

mQINBFoM1hwBEADsoMQvDehbuaS9vyTWe0fj2/7Ny+3UEa1F/CnLyxIk84yT1ztUoBSd4G9F
itClHmylmLrLY2vT9ck5MYIQqwECqlLRcKieXLUyz1Rkq28vDxYr6cXZkNAsqZEXMRdLsfAD
JQOHvi0B85wq8TToJx5H/ySBvhzSiqPPDIfmMfnsx8uOUW2Z1yCtS9Te1MkB88jP890OOxxR
UU3U6U5OJ3zovYIxgbK6wwIoajkGGxfwIDYluzVkni/zAN7elYHu2uwjKkxC2BF7Q6zhBFnm
R07NhXTqOldQ4YIGpHbj67gQE7yFpl1zkJJcFGlkDiMVALaqJmwIy+hToOFglU1jwTaCtMCt
2Xhvl2F2tSl3wRynk4Wj1QVoQNdcXkats13aYc7Op8AHz2RKmNXT/LgvK2fnjUuSt8b8nB6F
zY35VTwY+NceK51C6EpydRCMY9xHzFf4r4kO/bABx3b9YIoNiLqUM+QEDihlZL3cCiAaLIiK
vOFIg/34YjLgRF9359KcCmcn8hNgM0VVvRbJhar9pJt4zIapq1qeMMRb7sNaib4lBaoHc0b6
NW9O1zHVt1sigXua0UHbfVrasE2aRgb3rgvTL8eNpWdB8IklO9xU9xslgqADmlunvr/iXEeu
avl9B+aBEndCF3LNVAagJkq119nIQaBU9bJ7OH70rU5LFfOMcwARAQABiHUEEBYIAB0WIQRo
t0M2IP+hSSYVPAg6ETAFrHIzYAUCW2LwWQAKCRA6ETAFrHIzYNq0AP4uLjWBwso5+0DY8jMw
SwgVEChqdbM6V3ITG+bIGBXWyAD/VtUwhM/0zV8wH0VqzXtOV+l3uwoj8biUXsqbue5iMwq0
TU1pY3Jvc29mdCBTZWN1cml0eSBOb3RpZmljYXRpb25zIDxzZWN1cml0eW5vdGlmaWNhdGlv
bnNAZS1tYWlsLm1pY3Jvc29mdC5jb20+iF0EEBECAB0WIQRjpAESzpPuyPcGwRhaL8eGCWAG
EgUCW1GYLgAKCRBaL8eGCWAGEjq3AKDSZMP8Fu+48OvL2/ymeYbHMojuMgCeIeSYHvsYIm0A
Ztp6bRjeRkTbr5+IXQQQEQIAHRYhBHS9Hs58WQASRiKdAaG8ZED3RHJjBQJa5sY7AAoJEKG8
ZED3RHJjmSwAoJFbpfOtq0ee0SEJygbLM/L16oUSAKDX/cuWBEd6ObMvMcr9XSQz5pzlmohd
BBARAgAdFiEExPPbSLTQX4iGg3mOCqBBbXwbh+wFAlqoFFQACgkQCqBBbXwbh+wJCgCeIwbn
9nVk6Hi60gGkesxMRw1Zw3cAoJK8QFoNWc9UC8VTQ88V3mcDWZYaiF4EEBEKAAYFAlopBS4A
CgkQFDrQrU9Qc4JDnAD/fTMUtxHQOunt9WwQZrvuRGekaTA+qL5/dk7AiXUltuMBAIRTkRL5
yKGVPx1gjHltMnbg5sfxVcIJ67qSZlBgLJ6/iHUEEBYIAB0WIQRot0M2IP+hSSYVPAg6ETAF
rHIzYAUCW2LwWQAKCRA6ETAFrHIzYNq0AP4uLjWBwso5+0DY8jMwSwgVEChqdbM6V3ITG+bI
GBXWyAD/VtUwhM/0zV8wH0VqzXtOV+l3uwoj8biUXsqbue5iMwqJARwEEAEKAAYFAlopIhsA
CgkQUwZrAgwj3uDvMQf/UX24HUDNzWkR6xwiYlCah3iXtICuAEJWDgvpbzGMmYqQYS4FoeCt
PBhJ7OeUg+YtXwuD2ctbbeq+srprjxtuPe6AegVq+O5Xk5SwEJYnkNTQKIn74NJrsFYcfXvu
4P4FF7hj4yuI8EZADMo5VT8PGS9sp2OtxV/81/GXBVHp9SVgGEqse9TcOkcRQKfWlScvsUhW
W5eTVIQscTxNgMVozl8IrXIYJrgNUH0G18BfuvTK9HUX8cdaRrN0cVXrQtg1QP99QaXk+KFO
9mf8Yq3wipBDu3g7H8HKeEI70/mnxVbzj92giOwKP8a6m4OjQkOU8GlyQlMtxvWVXW6RgBU3
UokBHAQQAQoABgUCWn6CmAAKCRDY2hlLtHh9PpY1B/9HBDJMmpsLcLF97PQZae8WGaRdkhya
7Jq3g9qtAn4sVeiWFYVGu8oSFomiNfK9XRGA7hXEgkNjsNSu8uMqgMuW6P36dXA4w6yJ8zHF
PVN/VCuUcNsOLSHamog3V+psTBSeSkUIcQ7gX5NgcveTf0A0/5t7cXC7EA2rayYNOKyOgkpg
q1WtHJgJKTQnSLwTDZIO/EV8Lu/usiTDsYVGpm6eH8XEjOVGAQ4EWxHaVPjN69Tg4eYFJJai
7prAmodACtc+rE39jiqKLbBqnvD7nPKCieFnt+7nkghBkcl2VbUEXXrP4xIecpcY9lMKNhJQ
RpB+N0/sHhSStBd4IZWYXBTfiQEcBBIBCAAGBQJaMDqZAAoJEMP2qyU7W7Bc8t8H/jS85Exf
M0+pqPmzHzyRc1DqCXG0Cm6vzc3f3GKHO9CIpx3wrZi5+yatEWCxqa4MCfJ0LpIjbNJuwo6l
sy+dim0SM8ZM0MtW8dXo9cXm6V6X5nWeb7fSL4QsVeDRTDKPKEjNqj4FdAa7JJpUGlO4N2im
KXsEegjXYNEG5cCrcVOY0dvF/kOEAHl2caPj/raPoKg+4XKFFNsVbPPSHTaj8TtRRu0z+gEH
9ZIaHW7fUVTqreLzaMCbhQFf3W0bVa+EVq7T1smtODc4VGYVd3i/g3dBqhDWmf/bGAx4DPaT
3xRrgc2EecC+KAdzQHYYmScnJggUVUVCLGJhl0qb9DIXLneJATMEEAEIAB0WIQQNvod80uF7
pMRrkHZyPNVF+Rh4YgUCWsLpnwAKCRByPNVF+Rh4YsNoCACSIrF0SFdEo+c4rcvnwbYpX1+b
KhjixeXqa1aHqEPvlYC47HQc1s/RmInlCCfop4pilq7gkw95iKnmWWwVSAsjQaLSOOnmurkG
0UYrez6KbfyDln0grleOyrDM5CRdFy8RZPrv6ShXQHZymtkYbon/DT0wnAygNox0oBngdgPY
IvfCi2htekXdQBujJEa543nF64UKiFCIenrtIwdnAKjbyv2/y084UKWQbOW4i9hCgI9LYjau
NnjtvLhbjb1DkY+LUEFK5Acaj0qmUnXyIoK6NHi9/ojr2+2SbrbVPJjToaYcSoIVdhAIm5pX
CwXgsUk6EyyWQHbvpaqsacEoOd4KiQEzBBABCAAdFiEEM9+fcgCQPxBfY0BefIRl+3qrqL4F
Alq95TgACgkQfIRl+3qrqL6f6QgAlflQt0NGLJwV6fmpTI2n1jTO3F9JSm2Ft5bwPPyc6iHH
AqY9jbEcm19cEK8ka+n/Mps8l+GbKMOnYpPUjYxHyvmHRz+DRF8aI//DdfJGz0X2jvgwm9uD
vuFPMuK7za2ST/T5ZxyEsl/W19EnXBZmryeyEauIH/AtGpKcC3+6LsGY5eUmP1IHdysienHx
PaoxnKjuqs0i7J5ZLxAdwh+N40AwjrkAhwz8uHYmOsqt/+lN8WT9z1tn8H2XNKkXaMPLh3vn
CAimGQEutHOHjNOJldDIxQ6Dn4Jl7xcUQOqyBzfEZGJIeGcYURGj/JvS0/KqfifERyIAQsqP
en2cXPCzRIkBMwQQAQgAHRYhBHDhc6Q9lb2ckT8Fa8xhplHgUgLnBQJaYWMlAAoJEMxhplHg
UgLnncYH/jNbR5er3AO+L3low9TNBwdwfEEx14VmgfqqQ3/FIHMORhz5C7unDFzLRTF+OQ/+
CMlDJPa0TiLD5PTB3SWWtjbJsb7zMMblQ65SpkNSScVONlrojQltWASdpqd6HpDCZ0xxT5kQ
AY2YOfZkE/4MOHDV7pGUZaVRN+cC6lV2H+gn7Zmp1/BrVFzOqcVXqvGC/pfRK89p8ZadOP9b
feHm6FmoeeTjX9cOKfgY1qQYFsL4X73WxUrwC/k0AomNj3M877AO46+3esPxBBWDbOrm/LFQ
9wZNMuIZP6rDCFcHDeqiDENixO7VdC1qdjH5GWQfBzIr4iJqamaCXtd3pUL43tuJATMEEAEI
AB0WIQSKjfs6e3EJpeg/FY06wZpFF7Py8AUCWmz6SwAKCRA6wZpFF7Py8CNECACWJAtahiwx
Amv+h3REvSEnhoZGUfRy3IAn2eaE7wgdMOTpySst0pVZBqdS7mbv9DSjN43tvazBNAGd5oT0
Wq0ml/ZBLlu2BGOziH7CmBhaOCmJf/kUzXxAvEX5QyUsAbf2FzkFwkJRl31qB6VJjYG9SJPv
qH98cxH6BHr92zbKOxbAjYJ9IaA+E0BeGz9W6eBlm/Akpz31jf7iJQnzhSU7SGVh4P7FPxbC
Fpik4ZvsA/doAtUDpIyRDoDz88NCaPNpA3X9LBe52A0N4dFWh1pca0oJEfJSpmOboeguuS2G
s2vJYqILs0zKfNuXERVZJL2LdJBjOQq4NCUulivAJApuiQEzBBABCAAdFiEEkbkmcjXSHFea
k7R+bBHoWsrJUAIFAlorrb0ACgkQbBHoWsrJUAKCowgAsMrXhMBKXEOD5d5sO1PaF+fzZ3we
tOUbNa3Xo8dZDjlQxcgq0BbgAcog+UnmZMiBkW8ouzL96T2q8XMdBn28DTzLkh3LIbqHSiq7
R0Eh+ojQfsi/pSYtj1wSsMcKBlYizcXtTGrnoUnh7EJriv8way4VSfJJU6bXmtLlIWlp9Se+
99Rm6JxZhxD3Glm7tLQMz+8QcZ32EV0sMKDnLTOgRgP3Wl62dbPvf8li4xgSZav2exYktuo8
6kOOGJuGByZq12SlLci8KxGUxE8HmDu3aJEvs9xYi8mTMGDjbYxPPOchzngEckcuU6Aq1CqM
7XyyFz3Kj2Yd6xKD9KrZLS1fyIkBMwQQAQgAHRYhBJJKcUb9EHj1hAk5RVdrCIaM4qDABQJb
TbYpAAoJEFdrCIaM4qDAujQIAKRqkkOdEl5zuO7IXldrjxGRmFyCGYZzMQ1KdjwPnBMcye4z
ioHxuQcKOXG6E9zYtMPNFwrYVNIibQV9F2C8o3ZaxROHTsx6x/DDzNJ0DZjR/eBywbRVjzGN
b7ALbLXPSiPMhit6osoJxEURUekT66Y30tQNNrTfTBXjaBSjfu+qtEjVMmTmHNidAxwCVvNo
duXb1MgSbQvCT7CO8FeKzHwcvGk64qu6Z9R22mcT9MDTpQzQr7/42Z4FVlW5nLLMgQw1+Utz
szxXdHxDP48gI6oxz4RPjV7qJ+avnAXtfK/i/KUjqpOAqWVgjoG+iFLBMk0LUydiLvK36fRs
0m6CwWmJAZwEEAEKAAYFAlphQp8ACgkQQNwg4GXiMBVczAv/XYMGxBWryH74MPwdupjllMiG
X8LfiZGkFtEtGUxgZVqesAiTJD+sjRRKVnzLlvRMqJgW11hnaB64xUwkK/PunoG8iF6ZLlqs
93I9vzV1G7WvBWoz3c4SWDIU02+YOzjTocEUPVzr2Y7DWMCGqtNmWcqgrqtuGALlG2i6Or3q
UBWmeH5PebGCLoDjgF4KHEIES0vcPqK16KmV++rujdH2rJKEnDpcKf6LwX4gBnLu3Sg/I2qU
/EZCqHq2jwgbSmBhp+h05jlXbSamrWokjeIExZBCm7rYCv7miDbJv0OfGEDcCNODTnp5DUtz
SrzRShDFIjkrxpw6UArfvb/V4/qm5SgfKKGnu1qpQrnX468LR63/ukNVNvydO+xVSb7tWRo2
2JnMOnRHJcPX3xM8lJg+5u/f10OfllV0FQPGUsQlLUiIV4iFQA5L3G/dd3ZEuTuohNLVK1C6
ZL6dIzvbCmD6B5ihrAJl+hKcXelPvJPkSU+EFoMfiIKurr4/E0dWvQ+biQIcBBABAgAGBQJa
VQxBAAoJEG6UMwc5Y8dtW2cP/A1uKRrhnQCdhF91wk69f9DvPbQdQG9JcMqamzrhTdN6ktCX
OFmci0KExFiUdM+XPOa/rrw/sFJS8P8OtljgTxuB5kh6gxtUmiZ4iB4X0RO0lI4tu7PqeXeZ
5uS2w+OYEMZ0n67RmRPihjV83ITF96jadLhqvIG4L3Tz22jFpeJkl95CnOtQwjA1uSJpk6Qg
gxlU1n+C4m4bh7TTps+0eXiPHBCXEMXFUcESmLrPUCzQ0m3vm6kJEw3styA9DsPlHn8Vqz4G
PbYtvH6/Ma26IKuAYAgELRpX/gxK8ohlqw7zVzZ+Rh0yXKDZd8AHYVDd/gXVZKvthiOCY2Ak
ifz+3qDF1YN/Me6xN6GDNwMBKJs3eY2lQUgvCb+XUUzQkb/u66hijX2cXH+GoW+DKbPQrUO/
OXTL/zbczNI4UTh6B0r6CW5E00gNWDmQQpsoxFPtsOuphwzScdLQzGcF1expnD0aPm4R8Hj0
WUt6Notr4Psce4c/uPpE7G+I/T7hpVp+PXp1Chk6uxgvvj0/NZec7fZ1wtWDBPnLM8ZRFzo/
FwpU2s4QDgqOSbyHzwY3vwgbbE5J+y8RYMlhmHhO+GcCyn6eJPYsH0tw/WnIq/+YNDLIHPAK
D4YRqEE0hIQ2xJHPQ0bMZyxGwMsZy6dy0Bt7KVfvDUKglotI2RY1xGClcyVMiQIcBBABCAAG
BQJatdbWAAoJEPBLjjbZ0vBcuxgP/25SzU8Lm0bnqU77/XMP1hKxdMfF4CAePrMI4yDY18b3
lxuxf6J46AKHrgdeF7ABNHG5htg5XGqURveTDI+7HRatkZOEiEDN0aFUMFRmOBoLljVAZBJw
7KJaH/d6Ey827uMq9deyUD0kKQVKOldijUv4Kao57e9pgZejwY9LfyhKXgU7vWy4JzsT1ehM
+M+Wt3vu8Zvnce5FEuaWyTTqw/uhLId+tGjLzfL6itC5EboBzRr+wO640neswBmX9Q6e68Uz
7sz3wJ1oRbLa0KlwU08j21r0KYqmy33x1BfCP8DhnEhg3tOxQ3WE0Z3XnMmpac8lMZNHE52W
O0eZABEAk3RJwnOIUpqP/qEajsuksT/BLuOhjxidcd8szNZobyCsE7QNT3ZNxDb8r//J7lot
lcWlSnSmd/wt9tb1QS5HwY7ec3EM91T7ZJsAYhK4MQ5ZdDRWnqIm9RZo4z5Q+1CenWJ22wEZ
6eFW2dYrsc5l3sYnK9eYddxEBLmI5i8Brgq7dPr2BEZlP15vw3hZSiqLkxDHKRViHsZAJ6Cj
98adRJFDDhtMAJRrSAhrw3ymUB4ZCeWATQayEg1g8vV7ZCULolfIL5Z2dKbo2jw02/0zWcla
EvdAUABogSg4Gzg0GLwAmUIhtVlbGtOwGahunVr4hsGfylTeLznLXWGZU/pPDqjKiQIcBBAB
CgAGBQJaa5blAAoJEJwTVZIRJdMd4YsQAJwPjXNoTQvHJdABjvaC7PXs20m23GWp1P75vYDD
iSuQ88QB0acl/7SYWLXxR5MpJAqCowOWK+vOXspivXupH+1PFW2vxjRUGkuI6I/Z41YVg3yT
SD/Cep9JpK9nUFeXNFwDjAB9mmMjioevMYKfecmWRKpsma9uX76/1Ew2XvRVeh/Q8Zzz55iI
ka4ZPLGpIJtRySKz5YH4sJnq7CaPGDdOmxOtkKdwSAtW9kHqEn1U8X2UDfuwN0oEeY7Q6trq
PeG6SnLgmfvZghSJfMgsTr9fPsEQCMBiVU0VkC+swPteHDk3AhjWHpxZPekGih17JIsBw2qv
4efWFqfRfwSL3+9loGzXqWmbqiauQ8iCh04VJltBTzqu0ftDlYu2SRcboa+w9PpJz6zC34C5
iCm8LC/lSv6fRiCKUwvzUT1hY9UPCG7gt/bumCB302dN0G60p/rmcFamxO5fBuSGutkG6WtS
ql8w4l0GtfQ7dTiaHCdxO1n0VHybdJRhdXN3KWKjvg68VG5218LVGJKB+a80rgdJk3+YR/C5
VP/w3jPqtZvCJxWWUz3pIIZpIshQCtNgdWq1CICeT0cGXnCadT+N8NA7kifJ1kssZ+bWn0kV
jEpOsM5KsG04rs0qKHbWS215+WTMfhZg1vwEA2IPgqnqrOnHs5gJ+LqVkPjghvxKNWVSiQIc
BBABCgAGBQJbL+o6AAoJEEgPMuc1t+7X6R0QAMLN7+/1qLYdiKJVzANVr6DTeqJFLT5vedd5
UksIqP0Gz0BvvAxj1MhZwfsCKB9or3Q3R/BlumyrXQon2dc8Pxc1uchIvGBsB5tBijo/QGSf
8Jp4t525SX92fJ14GgSnTlnbAJ4o4nLLasWv25pZXBN8NswQpqVZVD0gYaEyInJ37fhrLrFl
JR41UHXY0U9h/6Ydr3vg0Jw0HjBinNHdXFWd4bma9bUM0dSf7cjneXe8gdS2Tc1mIi1VIzBM
YfzSQE5G+7Re9u3yJe2dIu7IO3nze+tgpowimnGoC0ptKmO8RBgKlrlmOrvq1A6tspC91s52
oidL/ue3v4yq6T3dpmZmkPIEgYX8SQkEE/j/EyqeYNqXKtibWn9xZWWohuVbyMGRGw1B9n2Z
5gSp3cKi9Nv1tjQeirMWC9uIHrMrquWbGu17E5z7fnWBih5gXxDdRmd+toTZ2WLAJYQFz9YF
ifPB4uQ9FK/5Qjx9CN65sLOI6ruMkD8NZ5KL5uLBKUHqc0D/Z6bTtziVm6AjevZqh/vCpW9o
o9sDh6W9RIcgKlWLJoaQtNpFj8+wyxMftSBwb31Im+dIcdG+E65fXOzv71GXsBAc4VJi3+4w
QPMN+8bU2pMnZDFMsMs1JVBj5uQ2CAlq6xJnsiAGChX0wcQWQAW3L6kqlumNfNAQR6AXiVP8
iQIzBBABCAAdFiEEfmuf8LZKAqM8gpb9gpHm/ZvBnscFAlsgxGUACgkQgpHm/ZvBnscXlBAA
imedlNHiVL0yAkOFk7V4Dt4R7eOaqE6QrQpfMKzwwItfO35pKSCZHqeLwWnsYAHsd4gjrN3T
ci+/xOZ0CY9fsKOV5PrLNBnifUF4eickPV2Nua4FU85SC8RDl0Nkdo9ISHti232spE5vMnJG
yDMLDiV0atnbcvAxVf4AfQ551J6W+GX0jBHUQMJ3cWwkF+ycKJ3/an5mmVfGgTWDNcp8NPwm
uWciGJsnIObeLChMuxC09iZ37iOaO/cqICzNXqp+4j0uMtPyHME1yUwS8wuuhTnzEo9zmobE
cPQcm3uCe0G/Tmr3BHJkmCnHd6Olg5YeiYXCgo6XvnEIQ5Y907fuv7RpFI2PZjTZld1sDdCT
hIRb6dYHeRsE9R4u36kfKT0h14pZp7VTapYJOKuP+qpViQG3RCdmWSYW5rjr6a+rTyT3PN84
rZ4KrkphiHBlduwro0HBejTznr2Gve09G9meTYWpCz5dJ4dQ6cqKUlAPriTs283wF1uHmlkl
Ojoys6gC2exq0PqndGEoCXdkDmrzyIxjLj9+9Typp7dbseKmQ/uhlGCvc/5zXmK1f8aScg25
+z0Mm7EAqEVrgUPlO5ExzqHNNE8fbYK15LxoJDvXNkBKxMfXTFi4MNqFV7kzSOQ6MmUtmIhE
I29xlqfUg2NaL+kuRK3NSMAcmTcF0Mt6Xm+JAjMEEAEIAB0WIQTC+kMN0MwMA7woOOBZugsX
mhaTXAUCW1rewgAKCRBZugsXmhaTXNrYEACVJBmXXgOre1F9oq6L5LMXTGTLaw+6SskthbKr
KL+/5gPslSz+XJ18nhdiKpMq284sIUmCa9gQ8paqreuU/e2O5wMn0/ZrFdI0DKK2wSrM/nlE
RMtqfVVkj2nsABLLLvrohqGFxQO/1dW/fhcNDv0uxTT4lKtxNyaqWjTDHsDcftdPAHy07r78
Z0VeLI1J/py7fGVOH/T/ulCg8KyjrkeINfzBOt1rMPKNI8PlQVfIofIbZ7FM29sjxZGiGyGS
iuNR3soLwh/8T4xEjz/W4JJFMNhVw77LxntQpPMAB7LmYSuMpU9zmHJ+0jPpKHp0DwSy60S+
BZB0iI3G02RhaokFhv/l9OX6ndxj0X9Kda5UOpBEl8gmcIRGIU1bs5B3RGOq9O4lXKNzuivj
FcFume5eFdYTxfiOzD/Oxi8dSK0YX1JBH81fQi7lyanz470E9YAuLwwEUZdzIbqVlx7TQF4f
hqr3AkG9DVnZvtvuNDQ4aZThEQZITtf0nI0Xwz3EhA52mV4pN7guWEnQUkY8ow4JfLfo+aEQ
onULpSuZzlHD39JQObnORoskWoZkHyvfCh57zptI7hQVPLX4NraF26aJ3c5sBrkqEw6JMb2c
DMTyBvRXSkGpIgLY8sODcZ1uTte4NCZN3dRZN0vxUsP/mTqEGAYhCkCP34Cvd4huK/U20IkC
MwQQAQgAHRYhBM9gvEBNWX8DMIZvqKo8Qg0d3DTCBQJbGY0eAAoJEKo8Qg0d3DTCVPoP/3a8
fMUi5jOD17bm6YOaEZcZOo+5Kh8/XtnTLDg5CzP332r0KDa82iiJY1lThVftw8Jvvh4XCRjW
V4XlqVTaUlB4hklggZI+r7ocS1pEqm15rqdymlR3+N1joKcsJads/IOhcl0M1Gas11SpBRHi
H7MXnW8fHS7ksa0O0/C+XqyCcVfJUJQKexaritx+Bw7zvcUjox2UQwg25o0c2u2Fk/2CFhtM
Q/etA+yQx6nzyk4IDfF4wuLUQSSuGgk1/38YjSeOafbjyRteXa4Gb2v9+G+477e5a3NFepo3
SvtC3nLPwn6RWiMSit1Eexmq9Fl7sHZR65d8jqY/PbqwAwdap0LX7W0t9FCXGIQ1DZNOsndj
ng9NmptGJ83BC5zuCaDqDOhOFJ9skkO2TwdaeRWrgw8WYI5p/iifrgu2jQ/OhbCHQ/bfMgb4
8cPwK0FwE4V/SPIGnHy85OO0V1HdJxXhEGj20p9yixXRWZGYqTbO2EtSGui7iEqbWB5MRsRL
oncipXrymEcN3TCwTIK/mi7mOO5qrHu1ZF2AK64lXzDguvGexUmnT0lwFNrcXhVRUI59iBC8
qx7d1o9TnR0BqQmQyAOCSLknq1Ld07bN4Ew8Kj3EheMq/ztIeJNdccJLKtZeaTfr9lKwOQvy
Jbrl8ymd0h8iqeuYBMheshdJws5mQxyciQIzBBABCgAdFiEEz2C8QE1ZfwMwhm+oqjxCDR3c
NMIFAlsZjP4ACgkQqjxCDR3cNMLAxBAA3llhfn4I682lL3DB4q4hnCZr8QbHQ4QWG5ZWDgij
HTURIx7ac2hyKYXnEHTF5SEYIjuQccisZ+onGqctQXsvbtLBmDJi3PUoHiEr/YvJBtOgCTnc
4UtAK1YrTRFKlbTH17baBb2LAn9W8wm6Y1UOGBTuDcNJOUtwk/mIjf1c/TBY8lUyMP4Ore2b
3mM7Pid/1Zo9h5PZvtJfY5B5OaYivxmGnF0DRZ5w6oJPDLJr6B9DLXYMHaQBJXTpeN/s3y1i
j9ffnNvJh6Q7JO51pLnZ19Vfs3rq8qL+0xt5oGDXjReLdu/654zcCsMx/5x7X7H/Rhl/Qvft
BuwpkNvThbBk7WYyREJXvaNo3fmEn3ApVFdud9a+O0zVp3FNQNRq5Vx5SzbYuQZzbwDepzUx
XxO0G5fUyDEEfisjm8hukL9axJGo3J0KRO+k7/INx+7wM+wWDKyW6Wu5jPYczuv6/MD2n5i8
hC6bCo84u6ApSmFcHmnLgfxFya5YA0c2WPh4ig+5Y2dgGue+Es4CLFvirHfqfPANkirNP4XG
9GTlCoMIDfEtlbnLL8+m6fo9EFB9vTA2Z3NnbFdcXrVaTvJTtE1IF9Fs8KLaLqX24Yc6fl3e
LTKrrD08KFAUJxF9IZ22QVYScVApfXm5eu757Ba2q9iAPTWC6gSN1FFI3/asfaXM1faJAlQE
EwEIAD4WIQQt7b2mPU6DP7YycpsQSI7at7Xy6AUCWgzWHAIbIwUJAfNvJAULCQgHAgYVCAkK
CwIEFgIDAQIeAQIXgAAKCRAQSI7at7Xy6LS2EADrZIm4s6y1Ejamgc5invqfft1NN/QvbPsc
dtWnPpfuZRtyi3GtBs3RFcP6MbynkfC9QSynfgSqhrsgSCr1hfgLAke4MRmSNnxGWtJpcUnQ
m2Y0HQ/f+smyWwTTCZG4RiF8evANeycSM7SQlRXUSRvMARh4VtaJdXvshWE5KjTn4ks0YqMv
4TnLHRxeA+LRAyhLXgMC2y8Oabz2A3N3cUfoFyolUhLkLCh3bmudMFXySB7f06LFWCyGFF1z
bduVkMVyiKEm5mKV8yGERag0b6Q6lKyq7dwzm0c9xvKLxudQqDF/Xcaf94SpibQoiHlU01ZE
EFVSX17FGUiRolm+iaevgU+qSY4HKwyks8YQvYa3BoJKR1lMtpASgsvdUJWBBv33BIkkTLM4
nPevz46UywoF69BdDZ4TsY8PI1XJcP92hm+VJ3NHnR7ecemUvkt5QNsn+oDZffZQX7zPSM3P
HIJ11sXyJSjHyyNvUpHVImqOI4tscUp8sGA6uV8OM2ywczATlOgd5MynWiwGC1d1BwixtsYg
Emsm2R+nB1xVLDx+ltKPcxQINsmLsgxXdXCWFx/50wCb2V8wajn9ayShk3SuuzyR95r1+cAw
kuJqJARSKQaU7XDFokVHzcUxaucgpfzmVNGOtHupY6LTwg5i0u0oSLB/GEqQSra9DyL5Ujik
l7kCDQRaDNYcARAAskrDQsvaz+yGtvPZhBeGh0J3eJsa1+k3NVNkMQbxwvQKahAvJvP1k+cb
68fYkjtP+foidQQf/AskVNT5XP5Gq5227/ZJfb5XA6wpchAo7UAU5mWuA+0NaJRLEJwPe3AZ
MxvMfg8dG1zh4p05FVzKPJAOaHRKQ7aNZqFfYDn0t82vObq2mGl0m0m4jlcwjyLYPfg71HuB
51H4GkaObhfKRyHEajUZqpx7gfXAXQ3f2vmsgpmCVcnAJuOentDF7BJieGbiE/a1MPjYzRsw
q6VgOqZWIrXNIc+smS8SdSYf1IHLG7MNmRV22twgdk3mim6Xwnz0ngw3CKVSeR24ggHFr/qh
PF1w066UTZP8kxAAGdO1MmS0s8Mw4qBqUTZyrR0dq4jJpZnLQze2gsXlykkKiGG8qpeske3u
1D1jBV/agWcbYoKk366ILRWkJ02ern0lxJS2wjV7GJPjTI6vZB3KR4n2AuyDmfAHT4QAMUi8
wmLUmLdRIbS17+f8UJieuyA/dFfW5+KVd/a+Pj1hXQAe8CQMvXYfWcyx0urrrfL3alENkYNi
zP3iPEkKGNFs5xL/hPUAzVtw0JbqmZdPkT73gllR5sDZfno3cVlKnOo/FZ/9oErxW4Nx9qPz
biGz7PIfTEs+vAwHDeWyf+R5xq88r3mLAtC3CVTEf9Kofid/OX8AEQEAAYh1BBAWCAAdFiEE
aLdDNiD/oUkmFTwIOhEwBaxyM2AFAlti8FkACgkQOhEwBaxyM2DatAD+Li41gcLKOftA2PIz
MEsIFRAoanWzOldyExvmyBgV1sgA/1bVMITP9M1fMB9Fas17Tlfpd7sKI/G4lF7Km7nuYjMK
iQI8BBgBCAAmFiEELe29pj1Ogz+2MnKbEEiO2re18ugFAloM1hwCGwwFCQHzbyQACgkQEEiO
2re18uj8SQ//XYI6u5gGcY2KeOBydzQUXykhUdOhjOxz1g+20pb4T2PbEKC7nv9292YqjM1u
W7EJLfsdOfbdSTywsWV9ZfM8OBkzacx2q8JR/s+Iihe6Tko+KtoPxxHLtFqIzgWf5lj4H+p1
8xJR8v8pkR3j8hZ8ye38MCc6Ya0ZWxg4jjYhxRhWugwOnz2bZC6ibRisN+BIWjwEN6c3NJ2t
ZObfxd4Q6gWCve7rHKNNDAI6bzH3+ODAcQx6TnFYvwxymwZKOliv0xMH2JyRJB/8BeLb+Bbd
bO9NgF8kJCH4DfdfRb5bSVNTNll0tf9GNB2OrI4DPEWumEVXXooGsSlOFIpnUmatsRMNeON5
C2BJVEZkKdSE3iszFX8+McasGYqj758Vz0NZA2NBsSZuVaOmpIi5jNP3wCOCPJVHiexHKi2x
qcSHWfCckChIR2nDg3vLO901+ukLDcWJ1yzKlKbIFjmI8U+rtqyF/KCw9wG78QmjAcUhwMrR
hzQVWdNsOQ3L3BSlb0t4Yi/ZQ2P1p/qoefSVwQfQeovCeUoSfZTM+Pw4GoSt8NTu6M5eSi7t
l9H13OiuYTTaZMzgXrD5hUJvn48Mo2hEMPsWYZDtH34/QNyTZi8YDs5rcRNz2TStAxpDg644
pjlGqsogpri/C2tSPloiRonu99lWyjZcwioRmqBv7QciSvc=
=2d8I
-----END PGP PUBLIC KEY BLOCK-----

### PR DESCRIPTION
**Pull request by krzyzanowskim**
- [x] Adopt Elliptic Curve RFC 6637 https://datatracker.ietf.org/doc/html/rfc6637
- [x] ECDH (X22519)
- [x] ECDSA
- [ ] NIST Curves
- [ ] Generate ECC keys
- [x] Signatures

Fixes #118, #108, #92 
External: https://github.com/mssun/passforios/issues/168

### CODE REVIEW

**Comment by awensaunders** [comment]
What are the next steps to get this PR merged in? I've only just come across this project through the fantastic pass for iOS app.

Cheers and thanks for the library!

**Comment by krzyzanowskim** [comment]
⏳&💵

**Comment by awensaunders** [comment]
> hourglass_flowing_sand&dollar

Fair. If you post something on bounty source or similar, ill pitch in a little.

**Comment by krzyzanowskim** [comment]
> If you post something on bounty source or similar, ill pitch in a little.
if I had💲for bounty source, I'd find time to finish it already ;)

**Comment by oliverFU** [comment]
Thank you for your work. I think ECC support is not easy. 
I have a (dirty) fix that your library does not crash when trying to parse an ECC key. May be it is helpful for others. Should I make a pull request?

**Comment by krzyzanowskim** [comment]
@oliverFU please do

**Comment by FlorianHardyDev** [comment]
Hello @krzyzanowskim ! 
Can you please merge this branch ? 
It would solve my problem (wrong generated pgp message) 🙏

**Comment by krzyzanowskim** [comment]
> Can you please merge this branch ?

not really. It's half backed

**Comment by MindTooth** [comment]
> > If you post something on bounty source or similar, ill pitch in a little.
> 
> if I had💲for bounty source, I'd find time to finish it already ;)

From what I can read, it's only 10 % when you withdraw cash.  Or am I reading the pricing wrong?

I'll gladly contribute some for the work.  ECC is the future. 👍

**Comment by UrsaDK** [comment]
I'd love to see a ECC/Ed25519 support implemented too! Like @MindTooth said, it is the way a lot of the applications are moving these days, with Ed25519 support being increasingly  demanded by the end user.

… and I'd be happy to contribute if contributions are required!

**Comment by mervyd** [comment]
#189

**Pull request merged**
