### PR TITLE
Compatibility to other clients and optional PGPModificationDetection

### PR DESCRIPTION
**Pull request by plaincode**
- Improved PGPModificationDetectionCodePacket detection
- Support integrity protected status
- Find the corresponding encryption key (subkey or fallback to primary key)
- Harden Signature verification
- Signature Verification: find the correct key by the issuerKeyID
- Remove NSLog output even in Debug Mode (led to confusion too often)
- Don't assume Literal Packets in CompressedDataPackets, but recursively dig into the compressed content
- Working on ZIP compression support
- Partial Packet Length Support and further analyze/warning fixes
- Removed newline transformation in PGPLiteralPacket, actually we would need to implement the <CR><LF> transformation inside the signature verification method. For now we trust that this should not be required as other clients do the transformation in advance, means this is usually not necessary in the signature verification itself.
- Fixed further warnings and little test extension
- Removed some (analyze) warnings
- Switch to standard (and updated) OpenSSL implementation
- Packet length generation: Marker byte was written once too much in the 5 octet case (for packet length > 8383)
- Extend library with One-Pass encryption with signing and decryption with verification

### CODE REVIEW

**Comment by krzyzanowskim** [comment]
I love this PR. Would you please rebase it so I can merge it to the branch - it has conflicts.
One thing - why you changed OpenSSL dependency? I favor OpenSSL-Universal because easy OSX dependency.

**Comment by krzyzanowskim** [comment]
Merged manually. THANKS! 
:+1:

**Comment by plaincode** [comment]
Hi Marcin,

i have to thank YOU, sorry, didn't have time yet to do it myself!!

Thanks again, i will take a look at the merge.

We also had a security audit with the library and got a few interesting open issues, i'll also take a look into those and will also forward it tomorrow to you (i think the audit might be in german but let's see :-) ).

Best regards

Peter

**Comment by krzyzanowskim** [comment]
Thank you @plaincode 
I found out that it's not passing `testEcnryptWithMultipleRecipients()` can you please look at this one too ?

**Pull request closed without merging**
