### PR TITLE
Bug fixed in expirationDate

### PR DESCRIPTION
**Pull request by dfrobese**
I like to add tom fixes about the expiration date in the PGPSingnaturePacket class.
First adding in `- (NSDate *)expirationDate`  the lines

`if (validityPeriodSubpacket == nil ) {
        validityPeriodSubpacket = [[self subpacketsOfType:PGPSignatureSubpacketTypeKeyExpirationTime] firstObject];
    }
`
to keep sure that the expiration date is taken from the key package alternatively.

Second there is a bug in the line
`if ([expirationDate compare:[NSDate date]] == NSOrderedDescending) {
        return YES;
    }
`
I must be changed to `NSOrderedAscending`

### CODE REVIEW

**Comment by krzyzanowskim** [comment]
i everythin with the PR?

**Comment by dfrobese** [comment]
Hmm I looks like I have no permission for pushing

Wakatobi:ObjectivePGP dfrobese$ git push https://github.com/krzyzanowskim/ObjectivePGP.git master
remote: Permission to krzyzanowskim/ObjectivePGP.git denied to dfrobese.
fatal: unable to access 'https://github.com/krzyzanowskim/ObjectivePGP.git/': The requested URL returned error: 403

**Comment by krzyzanowskim** [comment]
@dfrobese I think you've made some mistake when creating PR. base is `ObjectivePGP2` branch, while changes seems to apply to `master`... anyway, it conflicts

**Comment by krzyzanowskim** [comment]
What with this one? the PR doesn't look good. If there is something to fix, please update the PR.

**Pull request closed without merging**
